version: "3.9"
services:
  nats-1:
    container_name: n1
    image: nats:latest
    entrypoint: /nats-server
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name n1 --cluster_name NATS1 --cluster nats://0.0.0.0:6222 --js --sd /data --routes nats://n1:6222 --http_port 8222"
  nats-2:
    container_name: n2
    image: nats:latest
    entrypoint: /nats-server
    ports:
      - "8223:8222"
      - "4223:4222"
    command: "--name n2 --cluster_name NATS2 --cluster nats://0.0.0.0:6222 --js --sd /data --routes nats://n2:6222 --http_port 8222"
