version: "3.9"
services:
  node-app:
    platform: linux/arm64
    container_name: j-mirror-main
    build:
      dockerfile: ./build/package/Dockerfile
    ports:
      - "8080:8080"
    networks: ["nats"]
  nats-1:
    image: synadia/jsm:nightly
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS1 --cluster nats://0.0.0.0:6222 --http_port 8222 --mirror nats://0.0.0.0:4222"
    networks: ["nats"]
    depends_on:
      - node-app
  nats-2:
    image: synadia/jsm:nightly
    ports:
      - "8223:8222"
      - "4223:4222"
    command: "--cluster_name NATS2 --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks: ["nats"]
    depends_on:
      - node-app

networks:
  nats:
    name: nats