version: "3.9"
services:
  nats-1:
    container_name: n1
    image: nats:latest
    entrypoint: /nats-server
    ports:
      - "4222:4222"
    command: --name n1 --cluster_name NATS1 --js --sd /data -p 4222
  nats-2:
    container_name: n2
    image: nats:latest
    entrypoint: /nats-server
    ports:
      - "4223:4222"
    command: --name n2 --cluster_name NATS2 --js --sd /data -p 4222
