version: "3.9"
services:
  nats-1:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS1 --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-2:
    image: nats
    ports:
      - "8223:8223"
    command: "--cluster_name NATS2 --cluster nats://0.0.0.0:6223 --http_port 8223 "
    networks: ["nats"]

networks:
  nats:
    name: nats