http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
input:
  label: "nats1"
  nats_jetstream:
    urls: [ "nats://127.0.0.1:4222" ]
    queue: ""
    subject: "snapp*"
    durable: ""
    stream: "snapp"
    bind: false
    deliver: all
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  label: "nats2"
  nats_jetstream:
    urls: [ "nats://127.0.0.1:4223" ]
    subject: "*"
logger:
  level: INFO
  format: logfmt
  add_timestamp: false
  static_fields:
    '@service': benthos
metrics:
  prometheus:
    use_histogram_timing: true
    histogram_buckets: []
    add_process_metrics: true
    add_go_metrics: true
    push_url: ""
    push_interval: ""
    push_job_name: benthos_push
    push_basic_auth:
      username: ""
      password: ""
    file_output_path: ""
  mapping: ""
tracer:
  none: {}
shutdown_timeout: 20s
